meta_product_name: "Flanr"
meta_title: "Flanr - Get lost"
meta_description: " Discover the hidden gems of a city or a countryside by going on an adventure and avoid the disadvantages of mass tourism."
meta_image: "11_ycsfzl.png" # should exist in `app/assets/images/`
